Stop hard-coding 'http' protocol for sync server interactions in AuthProvider.ts
local-first-web/auth pull request #106
Opened 2024-05-17 14:34 UTC by brentkeller

### Solves

We're unable to properly connect to sync servers hosted with TLS because the `AuthProvider` is always trying to make certain requests using `http://`.

### Description

I've added a private method in `AuthProvider.ts` to determine which protocol to use based on the given server url we're working with. In this case I'm making a simple check that returns "http" if the url contains "localhost" and otherwise defaults to "https".

2024-05-20 16:23 UTC, HerbCaudill requested changes

2024-05-20 16:31 UTC, brentkeller commented on packages/auth-provider-automerge-repo/src/AuthProvider.ts
> +    return url?.includes('localhost') ? 'http' : 'https'
Hmm, in that case maybe we should add a setting for the protocol? Assuming everyone uses `192.168.x.x` doesn't seem like a great idea. That wouldn't work on my home network, for example.

2024-05-23 15:58 UTC, HerbCaudill commented
Looks good. 

I've changed `AuthProvider.#parseServer` to a stand-alone helper function, `buildServerUrl`. Since this is a pure function (not dependent on any class members) it doesn't need to be a method on the class, can just be a stand-alone utility function. 

Also this way it can be easily tested in isolation - I've added a couple of simple tests for the heck of it.

2024-05-23 15:58 UTC, HerbCaudill approved these changes

2024-05-23 15:58 UTC, merged